# Generated by Django 4.2.5 on 2023-11-02 15:07

from django.db import migrations, models
import statistics101.utils
from django.utils import timezone
from datetime import timedelta


def expiry_date_default():
    """
    Function returns the default expiry time for User objects
    """
    exp_date = timezone.now() + timedelta(days=60)
    exp_date = exp_date.replace(hour=23, minute=59, second=59)
    return exp_date


class Migration(migrations.Migration):
    dependencies = [
        ("statistics101", "0002_alter_source_fulldate"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="date_expiration",
            field=models.DateTimeField(default=expiry_date_default),
        ),
    ]
