# Generated by Django 4.2.5 on 2023-11-03 14:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statistics101', '0003_user_date_expiration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='source',
            name='Author',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='source',
            name='Month',
            field=models.IntegerField(blank=True, default=2023, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)]),
        ),
        migrations.AlterField(
            model_name='source',
            name='PagenumberFrom',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='source',
            name='PagenumberTo',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='source',
            name='Publisher',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='source',
            name='SourceType',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='source',
            name='Year',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1850), django.core.validators.MaxValueValidator(2100)]),
        ),
    ]
