# Generated by Django 4.2.5 on 2023-11-03 14:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statistics101', '0004_alter_source_author_alter_source_month_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='source',
            name='Month',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)]),
        ),
        migrations.AlterField(
            model_name='source',
            name='Year',
            field=models.PositiveSmallIntegerField(default=2023, validators=[django.core.validators.MinValueValidator(1850), django.core.validators.MaxValueValidator(2100)]),
        ),
    ]
