# Generated by Django 4.2.5 on 2023-11-25 23:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('statistics101', '0006_variable_sample_proportion_population_datapoint_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='population',
            name='population_description',
        ),
        migrations.RemoveField(
            model_name='sample',
            name='sample_description',
        ),
        migrations.RemoveField(
            model_name='variable',
            name='variable_description',
        ),
    ]
