# Generated by Django 4.2.5 on 2023-11-27 10:35

from django.db import migrations, models
import statistics101.models


class Migration(migrations.Migration):

    dependencies = [
        ('statistics101', '0007_remove_population_population_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='date_expiration',
            field=models.DateTimeField(default=statistics101.models.expire_date_default),
        ),
    ]
