# Generated by Django 4.2.5 on 2023-11-27 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statistics101', '0008_alter_user_date_expiration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datapoint',
            name='idividual_id',
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
