# Generated by Django 4.2.5 on 2023-11-29 22:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("statistics101", "0009_alter_datapoint_idividual_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="variable",
            name="parent_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="variable",
                to="contenttypes.contenttype",
            ),
        ),
    ]
