# Generated by Django 4.2.5 on 2023-12-03 10:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("statistics101", "0012_alter_variable_variable_mean_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="population",
            name="population_type",
            field=models.PositiveIntegerField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="population",
            name="upload_complete",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="sample",
            name="sample_type",
            field=models.PositiveIntegerField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="sample",
            name="upload_complete",
            field=models.BooleanField(default=False),
        ),
    ]
