# Generated by Django 4.2.5 on 2023-12-03 15:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("statistics101", "0013_population_population_type_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="proportion",
            name="is_mode",
        ),
        migrations.AddField(
            model_name="proportion",
            name="idividual_id",
            field=models.CharField(default=django.utils.timezone.now, max_length=150),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="proportion",
            name="value_count",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
