# Generated by Django 4.2.5 on 2023-12-03 15:13

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "statistics101",
            "0014_remove_proportion_is_mode_proportion_idividual_id_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="proportion",
            old_name="idividual_id",
            new_name="individual_id",
        ),
    ]
