# Generated by Django 4.2.5 on 2023-12-03 17:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("statistics101", "0015_rename_idividual_id_proportion_individual_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="variable",
            name="variable_name",
            field=models.CharField(max_length=50),
        ),
    ]
