# Generated by Django 4.2.5 on 2023-12-04 22:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("statistics101", "0017_rename_value_datapoint_variable_value_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="datapoint",
            name="proportion_count",
        ),
        migrations.RemoveField(
            model_name="datapoint",
            name="proportion_perc",
        ),
        migrations.AddField(
            model_name="datapoint",
            name="proportion",
            field=models.FloatField(
                blank=True,
                null=True,
                validators=[django.core.validators.MinValueValidator(0.0)],
            ),
        ),
    ]
