# Generated by Django 4.2.5 on 2023-12-04 23:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("statistics101", "0018_remove_datapoint_proportion_count_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="variable",
            name="parent_type",
        ),
        migrations.AddField(
            model_name="sample",
            name="is_population",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="sample",
            name="population_size",
            field=models.PositiveIntegerField(default=None),
        ),
        migrations.AlterField(
            model_name="variable",
            name="parent_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="variable",
                to="statistics101.sample",
            ),
        ),
        migrations.DeleteModel(
            name="Population",
        ),
    ]
