# Generated by Django 4.2.5 on 2023-12-13 21:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("statistics101", "0020_alter_sample_population_size"),
    ]

    operations = [
        migrations.AlterField(
            model_name="datapoint",
            name="update_dt",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name="datapoint",
            name="upload_dt",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="sample",
            name="update_dt",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name="sample",
            name="upload_dt",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="variable",
            name="update_dt",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name="variable",
            name="upload_dt",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
