# Generated by Django 4.2.5 on 2023-12-13 21:54

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "statistics101",
            "0021_alter_datapoint_update_dt_alter_datapoint_upload_dt_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="datapoint",
            old_name="idividual_id",
            new_name="individual_id",
        ),
    ]
