# Generated by Django 4.2.5 on 2023-12-23 16:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("statistics101", "0022_rename_idividual_id_datapoint_individual_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sample",
            name="UserID",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sample_owner",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
