# Generated by Django 4.2.5 on 2024-01-09 20:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "statistics101",
            "0024_remove_tsfloat_tsmetaid_remove_tsint_tsmetaid_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="source",
            name="Year",
            field=models.PositiveSmallIntegerField(
                default=2024,
                validators=[
                    django.core.validators.MinValueValidator(1850),
                    django.core.validators.MaxValueValidator(2100),
                ],
            ),
        ),
    ]
